### PR TITLE
Removing version from API calls.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
In this case it should specify where to find out the current api version. But as we change the api version quite rarely, i think it would be fine to put it directly in the docs, just need to remember to update it.

**Comment by dessalines** [comment]
They can find the version by going to the API docs, which they'll have to do no matter what.

**Comment by Nutomic** [comment]
You mean https://join-lemmy.org/api/ ? Dont see it there.

**Comment by dessalines** [comment]
K added a line for this.

**Comment by dessalines** [comment]
Weird error.... how do we get the yerbamate drone to use a newer rust version?

**Comment by Nutomic** [comment]
You need to rebase to get the latest drone.yml (was already updated since you opened this pr).

**Pull request merged**
