### PR TITLE
Remove latest tag for mlc image.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by Nutomic** [comment]
As mentioned in the other PR, this wont change anything as it will use `latest` by default. Change to 0.16.3 which is the latest version.

**Comment by dessalines** [comment]
Done, but I'd prefer to use the `stable` versions on all of these, so that we don't have to update them manually when a new tag comes out.

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
Which `stable` version do you mean? You can see on [docker hub](https://hub.docker.com/r/becheran/mlc/tags) that there is only `latest` and numbered versions.

**Comment by dessalines** [comment]
Not just for this one, but for all docker tags. By stable I just mean untagged / without a version, so whatever they decide is latest.

**Comment by Nutomic** [comment]
Is there any way to decide that? Afaik `becheran/mlc` is always the same as `becheran/mlc:latest`.

**Comment by dessalines** [comment]
Read about it a bit more, and you're correct, they're the same. Ideally tho they should only be pushing to latest for official releases, not to simulate a `nightly` tag. Either way its just cleaner to remove these `:latest` 's on all images.

**Pull request merged**
