### PR TITLE
caddy config fixes

### PR DESCRIPTION
**Pull request by nycterent**
fixed bracked. rechecked changes - caddy-common is not missing (at least visible in rich diff)

### CODE REVIEW

**Comment by Nutomic** [comment]
Not visible for me...

**Comment by nycterent** [comment]
it is probably due to the fact that i have made a diff from main and not from the PR where i have made a (first) mistake, full file can be seen here: https://github.com/LemmyNet/lemmy-docs/blob/f750d26fcbcf14601a9ee4c267a26bd11c695631/src/administration/caddy.md

**Comment by nycterent** [comment]
i think so

m

**Comment by Tmpod** [comment]
Doesn't this just add indentation? :thinking:

**Comment by nycterent** [comment]
i remember there have been a problem with a bracket, seems like this one is
not needed:
https://github.com/LemmyNet/lemmy-docs/pull/229/files#diff-16caaefa639d8ed96496b9805e6de1f1a4079e817dc180ecc554a10e46f83bb5L22

**Comment by dessalines** [comment]
See nutomics comment above.

**Pull request closed without merging**
