### PR TITLE
add ranking algo docs

### PR DESCRIPTION
**Pull request by RayBB**
closes https://github.com/LemmyNet/lemmy-docs/issues/195

### CODE REVIEW

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
Doesn't seem to like that this one is missing: `src/en/users/08-ranking-algo.md (41, 1) => rank_algorithm.png`

I'm rerunning it just in case.

**Comment by Nutomic** [comment]
I think this fits better in the contributors section. For many users all this math will be too complicated.

**Comment by Nutomic** [comment]
Can you also link this from `users/03-votes-and-ranking.html`?

**Comment by RayBB** [comment]
Added a link from that users page. Also fixed this image problem. Everything looks good to go now. @Nutomic

**Pull request merged**
